version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: cms-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "4000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: cms-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
